# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

title:              Luis Puerto's Gratitude Journal
email:              luis@luispuerto.net
description:        A blog about gratitude and what I'm grateful about
author:             Luis Puerto
baseurl:            ""
url:                "https://gratitude.luispuerto.net"

# Social Profiles
twitter_username:   lpuerto
github_username:    luispuerto
facebook_username:  
linkedin_username:  lpuerto

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
