# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

title:              Luis Puerto's Gratitude Journal
email:              luis@luispuerto.net
description:        A blog about gratitude and what I'm grateful about
author:             Luis Puerto
baseurl:            ""
url:                "https://gratitude.luispuerto.net"
repository:         luispuerto/gratitude.luispuerto.net

# Social Profiles
twitter_username:   lpuerto
github_username:    luispuerto
facebook_username:  
linkedin_username:  lpuerto

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
timezone: UTC # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
include: 
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .jekyll-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README.*
  - staticman.yml
  - tmp
  - TODO.*


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  math_engine: mathjax
  math_engine_opts: # more info: https://kramdown.gettalong.org/math_engine/mathjax.html
    preview: false
    preview_as_code: false 
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Footer
footer: 
  license: 
    url: "/license" # to your licenses page or any other you want. 
    code:
      icon: "fab fa-osi"
    content:
      icon1: "fab fa-creative-commons"
      icon2: "fab fa-creative-commons-by"
      icon3: "fab fa-creative-commons-nc"
      icon4: "fab fa-creative-commons-sa"